# ---------- 1. Deps (cached) ----------
FROM node:24-alpine AS deps
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@11.24.0 --activate
# better-sqlite3 needs python/make/g++ on alpine (kept in deps only)
RUN apk add --no-cache python3 make g++ py3-setuptools
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm install --frozen-lockfile

# ---------- 2. Build ----------
FROM node:24-alpine AS build
WORKDIR /app
RUN corepack enable && corepack prepare pnpm@11.24.0 --activate
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Build CSS, Adonis bundle, and embeddable widget in one go
# - tailwindcss CLI -> public/tailwind.css --minify
# - ace build      -> build/ (compiled Adonis app)
# - vite --config vite.widget.config.ts -> public/widget/v1/widget.js
RUN --mount=type=cache,id=pnpm-store,target=/root/.local/share/pnpm/store \
    pnpm build

# Prune to production deps for the runtime image
RUN pnpm prune --prod

# ---------- 3. Runtime (minimal) ----------
FROM node:24-alpine AS runtime
WORKDIR /app
ENV NODE_ENV=production \
    PORT=3333 \
    HOST=0.0.0.0

# Security: non-root
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Only what the server needs at runtime
COPY --from=build --chown=appuser:appgroup /app/build ./build
COPY --from=build --chown=appuser:appgroup /app/node_modules ./node_modules
COPY --from=build --chown=appuser:appgroup /app/package.json ./package.json
# Static assets generated by the build
COPY --from=build --chown=appuser:appgroup /app/public ./public
COPY --from=build --chown=appuser:appgroup /app/resources ./resources
# Keep .env.example as reference, real env comes from `docker run --env-file` / orchestrator
COPY --chown=appuser:appgroup .env.example ./.env.example

# Adonis needs APP_KEY at runtime; healthcheck (no dedicated /health route, use /)
EXPOSE 3333
HEALTHCHECK --interval=30s --timeout=3s --retries=3 \
  CMD node -e "fetch('http://127.0.0.1:'+(process.env.PORT||3333)+'/').then(r=>process.exit(r.status<500?0:1)).catch(()=>process.exit(1))"

USER appuser

# Run migrations then start (ace handles graceful shutdown)
# If you use an external migration job, replace with: CMD ["node","build/bin/server.js"]
CMD ["sh","-c","node build/ace.js migration:run --force && node build/bin/server.js"]
