/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AdminReports: () => import('#controllers/admin_reports_controller'),
  Inbox: () => import('#controllers/inbox_controller'),
  IntegrationPages: () => import('#controllers/integration_pages_controller'),
  Integrations: () => import('#controllers/integrations_controller'),
  Messages: () => import('#controllers/messages_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Overview: () => import('#controllers/overview_controller'),
  Portal: () => import('#controllers/portal_controller'),
  PublicReports: () => import('#controllers/public_reports_controller'),
  ReportPages: () => import('#controllers/report_pages_controller'),
  ReportTemplates: () => import('#controllers/report_templates_controller'),
  Session: () => import('#controllers/session_controller'),
  TemplatePages: () => import('#controllers/template_pages_controller'),
  Webhook: () => import('#controllers/webhook_controller'),
  WidgetConfig: () => import('#controllers/widget_config_controller'),
  WidgetTemplates: () => import('#controllers/widget_templates_controller'),
}
