/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AllowedOriginSchema extends BaseModel {
  static $columns = ['id', 'origin', 'projectId'] as const
  $columns = AllowedOriginSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare origin: string
  @column()
  declare projectId: number
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'keyHash', 'label', 'projectId', 'revokedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column()
  declare label: string | null
  @column()
  declare projectId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class ConversationSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'reportId', 'updatedAt'] as const
  $columns = ConversationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reportId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MessageSchema extends BaseModel {
  static $columns = [
    'authorId',
    'authorType',
    'body',
    'conversationId',
    'createdAt',
    'direction',
    'emailMessageId',
    'id',
    'inReplyTo',
  ] as const
  $columns = MessageSchema.$columns
  @column()
  declare authorId: number | null
  @column()
  declare authorType: string
  @column()
  declare body: string
  @column()
  declare conversationId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare direction: string
  @column()
  declare emailMessageId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inReplyTo: string | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'id', 'readAt', 'type', 'updatedAt', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ProjectSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'id',
    'name',
    'ownerId',
    'requireEmailVerification',
    'slug',
    'updatedAt',
  ] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare requireEmailVerification: boolean
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportFieldValueSchema extends BaseModel {
  static $columns = ['fieldKey', 'id', 'reportId', 'value'] as const
  $columns = ReportFieldValueSchema.$columns
  @column()
  declare fieldKey: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reportId: string
  @column()
  declare value: string | null
}

export class ReportTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'name', 'projectId', 'updatedAt'] as const
  $columns = ReportTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportSchema extends BaseModel {
  static $columns = [
    'assigneeId',
    'browserInfo',
    'consoleErrors',
    'createdAt',
    'id',
    'networkErrors',
    'pageUrl',
    'priority',
    'projectId',
    'replyToToken',
    'reporterEmail',
    'reporterVerifiedAt',
    'screenshotUrl',
    'status',
    'templateId',
    'title',
    'updatedAt',
    'verificationSentAt',
    'verificationToken',
  ] as const
  $columns = ReportSchema.$columns
  @column()
  declare assigneeId: number | null
  @column()
  declare browserInfo: any | null
  @column()
  declare consoleErrors: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare networkErrors: any | null
  @column()
  declare pageUrl: string | null
  @column()
  declare priority: string
  @column()
  declare projectId: number
  @column()
  declare replyToToken: string | null
  @column()
  declare reporterEmail: string | null
  @column.dateTime()
  declare reporterVerifiedAt: DateTime | null
  @column()
  declare screenshotUrl: string | null
  @column()
  declare status: string
  @column()
  declare templateId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare verificationSentAt: DateTime | null
  @column()
  declare verificationToken: string | null
}

export class TeamMemberSchema extends BaseModel {
  static $columns = [
    'acceptedAt',
    'createdAt',
    'email',
    'id',
    'inviteToken',
    'invitedAt',
    'projectId',
    'role',
    'updatedAt',
    'userId',
  ] as const
  $columns = TeamMemberSchema.$columns
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inviteToken: string | null
  @column.dateTime()
  declare invitedAt: DateTime | null
  @column()
  declare projectId: number
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class TemplateFieldSchema extends BaseModel {
  static $columns = [
    'id',
    'isRequired',
    'key',
    'label',
    'options',
    'reportTemplateId',
    'showIf',
    'sortOrder',
    'type',
  ] as const
  $columns = TemplateFieldSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRequired: boolean
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare options: any | null
  @column()
  declare reportTemplateId: number
  @column()
  declare showIf: any | null
  @column()
  declare sortOrder: number
  @column()
  declare type: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class WebhookSubscriptionSchema extends BaseModel {
  static $columns = [
    'active',
    'createdAt',
    'events',
    'id',
    'projectId',
    'secret',
    'updatedAt',
    'url',
  ] as const
  $columns = WebhookSubscriptionSchema.$columns
  @column()
  declare active: boolean
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({
    prepare: (value: string[]) => JSON.stringify(value ?? []),
    consume: (value: string | string[]) =>
      Array.isArray(value) ? value : value ? JSON.parse(value) : [],
  })
  declare events: string[]
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare projectId: number
  @column()
  declare secret: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare url: string
}
