/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AllowedOriginSchema extends BaseModel {
  static $columns = ['id', 'origin', 'projectId'] as const
  $columns = AllowedOriginSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare origin: string
  @column()
  declare projectId: number
}

export class ApiKeySchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'keyHash', 'label', 'projectId', 'revokedAt'] as const
  $columns = ApiKeySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare keyHash: string
  @column()
  declare label: string | null
  @column()
  declare projectId: number
  @column.dateTime()
  declare revokedAt: DateTime | null
}

export class ProjectSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'name', 'ownerId', 'slug', 'updatedAt'] as const
  $columns = ProjectSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare ownerId: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ReportTemplateSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'isDefault', 'name', 'projectId', 'updatedAt'] as const
  $columns = ReportTemplateSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare projectId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TemplateFieldSchema extends BaseModel {
  static $columns = [
    'id',
    'isRequired',
    'key',
    'label',
    'options',
    'reportTemplateId',
    'showIf',
    'sortOrder',
    'type',
  ] as const
  $columns = TemplateFieldSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isRequired: boolean
  @column()
  declare key: string
  @column()
  declare label: string
  @column()
  declare options: any | null
  @column()
  declare reportTemplateId: number
  @column()
  declare showIf: any | null
  @column()
  declare sortOrder: number
  @column()
  declare type: string
}

export class UserSchema extends BaseModel {
  static $columns = [
    'createdAt',
    'email',
    'fullName',
    'id',
    'password',
    'role',
    'updatedAt',
  ] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
