/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type ReportTemplateTransformer from '#transformers/report_template_transformer'
import type ReportTransformer from '#transformers/report_transformer'
import type TemplateFieldTransformer from '#transformers/template_field_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type ReportTemplate = InferData<ReportTemplateTransformer>
  export namespace ReportTemplate {
    export type Variants = InferVariants<ReportTemplateTransformer>
  }
  export type Report = InferData<ReportTransformer>
  export namespace Report {
    export type Variants = InferVariants<ReportTransformer>
  }
  export type TemplateField = InferData<TemplateFieldTransformer>
  export namespace TemplateField {
    export type Variants = InferVariants<TemplateFieldTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
